In [1]:
#Import Dependencies

import pandas as pd
import numpy as np

In [2]:
#name CSVs

brew1 = "Output/brewery_data_10.csv"
brew2 = "Output/brewery_data_20.csv"
brew3 = "Output/brewery_data_30.csv"
brew4 = "Output/brewery_data_40.csv"
brew5 = "Output/brewery_data_50.csv"
brew6 = "Output/brewery_data_60.csv"
brew7 = "Output/brewery_data_70.csv"
brew8 = "Output/brewery_data_80.csv"
brew9 = "Output/brewery_data_90.csv"
brew100 = "Output/brewery_data_100.csv"
brew11 = "Output/brewery_data_110.csv"

In [3]:
#read in named CSVs

brew10 = pd.read_csv(brew1)
brew20 = pd.read_csv(brew2)
brew30 = pd.read_csv(brew3)
brew40 = pd.read_csv(brew4)
brew50 = pd.read_csv(brew5)
brew60 = pd.read_csv(brew6)
brew70 = pd.read_csv(brew7)
brew80 = pd.read_csv(brew8)
brew90 = pd.read_csv(brew9)
brew_10 = pd.read_csv(brew100)
brew110 = pd.read_csv(brew11)

In [4]:
#List of DFs
DFs = [brew10, brew20, brew30, brew40, brew50, brew60, brew70, brew80, brew90, brew_10, brew110]

In [5]:
df = pd.concat(DFs, axis=0)

In [6]:
df1 = df.reset_index(drop=True)

In [7]:
df1.count()

Brewery Name        730
City                730
State               730
Country             730
Year Established    730
In Business?        730
Closed?             730
dtype: int64

In [8]:
df1.dtypes

Brewery Name        object
City                object
State               object
Country             object
Year Established     int64
In Business?        object
Closed?             object
dtype: object

In [9]:
df1

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
0,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N
1,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
2,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N
3,4S Ranch,San Diego,California,UNITED STATES,1989,Y,N
4,7 Cent Brewing,Gisborne South,Victoria,AUSTRALIA,2012,Y,N
5,7 Fjell Bryggeri,BÃ¸nes,Hordaland,NORWAY,2013,Y,N
6,7 Mile Brewery,Rio Grande,New Jersey,UNITED STATES,2016,Y,N
7,810 Meadworks,Medina,New York,UNITED STATES,2014,Y,N
8,84th Street Brewing Company,Lake Stevens,Washington,UNITED STATES,2014,Y,N
9,Abashiri Beer,Abashiri,Hokkaido,JAPAN,2007,Y,N
10,Aberrant Ales,Howell,Michigan,UNITED STATES,2017,Y,N
11,Able Baker Brewing Company,Henderson,Nevada,UNITED STATES,2016,Y,N
12,Accomplice Beer Company,Cheyenne,Wyoming,UNITED STATES,2016,Y,N
13,Addison,Addison,Texas,UNITED STATES,2013,Y,N
14,Adobe Creek Brewing Company,Novato,California,UNITED STATES,2017,Y,N
15,Adventure Brewing North,Fredericksburg,Virginia,UNITED STATES,2013,Y,N
16,Adventure Brewing South,Fredericksburg,Virginia,UNITED STATES,2013,Y,N
17,Alagoinhas,['null'],['null'],['null'],1994,['null'],['null']
18,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N
19,Albany Brewery,Albany,Georgia,UNITED STATES,1895,Y,N
20,127 Brewing,Jackson,Michigan,UNITED STATES,2014,Y,N
21,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N
22,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
23,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N
24,4S Ranch,San Diego,California,UNITED STATES,1989,Y,N
25,7 Cent Brewing,Gisborne South,Victoria,AUSTRALIA,2012,Y,N
26,7 Fjell Bryggeri,BÃ¸nes,Hordaland,NORWAY,2013,Y,N
27,7 Mile Brewery,Rio Grande,New Jersey,UNITED STATES,2016,Y,N
28,7th Street Brew House,Redmond,Oregon,UNITED STATES,1994,Y,N
29,810 Meadworks,Medina,New York,UNITED STATES,2014,Y,N
...,...,...,...,...,...,...,...
700,Main Brewery,Bright,Victoria,AUSTRALIA,2005,Y,N
701,Main Brewery,['null'],['null'],['null'],2014,['null'],['null']
702,Main Brewery,['null'],['null'],['null'],2010,['null'],['null']
703,Main Brewery,Centerville,Ohio,UNITED STATES,2012,Y,N
704,Main Brewery,Seattle,Washington,UNITED STATES,2010,Y,N
705,Main Brewery,Pilot Point,Texas,UNITED STATES,2015,Y,N
706,Main Brewery,Pensacola,Florida,UNITED STATES,2017,Y,N
707,Main Brewery,Burbank,California,UNITED STATES,2018,Y,N
708,Main Brewery,Greeley,Colorado,UNITED STATES,2018,Y,N
709,Main Brewery,Indianapolis,Indiana,UNITED STATES,2010,Y,N
710,Main Brewery,Carson,Washington,UNITED STATES,2008,N,Y
711,Main Brewery,Austin,Texas,UNITED STATES,2012,Y,N
712,Main Brewery,Torrance,California,UNITED STATES,2013,Y,N
713,Main Brewery,Tampa,Florida,UNITED STATES,2014,Y,N
714,Main Brewery,Hesperia,California,UNITED STATES,2015,Y,N
715,Main Brewery,Minneapolis,Minnesota,UNITED STATES,1997,Y,N
716,Main Brewery,Kill Devil Hills,North Carolina,UNITED STATES,2001,Y,N
717,Main Brewery,Speedway,Indiana,UNITED STATES,2012,Y,N
718,Main Brewery,Taylors,South Carolina,UNITED STATES,2016,Y,N
719,Main Brewery,Spearfish,South Dakota,UNITED STATES,2007,Y,N
720,Main Brewery,Waconia,Minnesota,UNITED STATES,2008,Y,N
721,Main Brewery,Marion,Wisconsin,UNITED STATES,2012,Y,N
722,Main Brewery,Lancaster,Pennsylvania,UNITED STATES,1978,Y,N
723,Main Brewery,Sainte Genevieve,Missouri,UNITED STATES,2008,Y,N
724,Main Brewery,Rincon,Puerto Rico,UNITED STATES,2013,Y,N
725,Main Brewery,Treviso,['null'],['null'],1766,['null'],['null']
726,Main Brewery,San Diego,California,UNITED STATES,2007,Y,N
727,Main Brewery,Aalen,['null'],['null'],1864,['null'],['null']
728,Main Brewery,['null'],['null'],['null'],2011,['null'],['null']
729,Main Brewery,San Diego,California,UNITED STATES,1995,Y,N

In [10]:
df2 = df1.replace("['null']", np.NaN)
df2

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
0,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N
1,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
2,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N
3,4S Ranch,San Diego,California,UNITED STATES,1989,Y,N
4,7 Cent Brewing,Gisborne South,Victoria,AUSTRALIA,2012,Y,N
5,7 Fjell Bryggeri,BÃ¸nes,Hordaland,NORWAY,2013,Y,N
6,7 Mile Brewery,Rio Grande,New Jersey,UNITED STATES,2016,Y,N
7,810 Meadworks,Medina,New York,UNITED STATES,2014,Y,N
8,84th Street Brewing Company,Lake Stevens,Washington,UNITED STATES,2014,Y,N
9,Abashiri Beer,Abashiri,Hokkaido,JAPAN,2007,Y,N
10,Aberrant Ales,Howell,Michigan,UNITED STATES,2017,Y,N
11,Able Baker Brewing Company,Henderson,Nevada,UNITED STATES,2016,Y,N
12,Accomplice Beer Company,Cheyenne,Wyoming,UNITED STATES,2016,Y,N
13,Addison,Addison,Texas,UNITED STATES,2013,Y,N
14,Adobe Creek Brewing Company,Novato,California,UNITED STATES,2017,Y,N
15,Adventure Brewing North,Fredericksburg,Virginia,UNITED STATES,2013,Y,N
16,Adventure Brewing South,Fredericksburg,Virginia,UNITED STATES,2013,Y,N
17,Alagoinhas,NaN,NaN,NaN,1994,NaN,NaN
18,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N
19,Albany Brewery,Albany,Georgia,UNITED STATES,1895,Y,N
20,127 Brewing,Jackson,Michigan,UNITED STATES,2014,Y,N
21,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N
22,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
23,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N
24,4S Ranch,San Diego,California,UNITED STATES,1989,Y,N
25,7 Cent Brewing,Gisborne South,Victoria,AUSTRALIA,2012,Y,N
26,7 Fjell Bryggeri,BÃ¸nes,Hordaland,NORWAY,2013,Y,N
27,7 Mile Brewery,Rio Grande,New Jersey,UNITED STATES,2016,Y,N
28,7th Street Brew House,Redmond,Oregon,UNITED STATES,1994,Y,N
29,810 Meadworks,Medina,New York,UNITED STATES,2014,Y,N
...,...,...,...,...,...,...,...
700,Main Brewery,Bright,Victoria,AUSTRALIA,2005,Y,N
701,Main Brewery,NaN,NaN,NaN,2014,NaN,NaN
702,Main Brewery,NaN,NaN,NaN,2010,NaN,NaN
703,Main Brewery,Centerville,Ohio,UNITED STATES,2012,Y,N
704,Main Brewery,Seattle,Washington,UNITED STATES,2010,Y,N
705,Main Brewery,Pilot Point,Texas,UNITED STATES,2015,Y,N
706,Main Brewery,Pensacola,Florida,UNITED STATES,2017,Y,N
707,Main Brewery,Burbank,California,UNITED STATES,2018,Y,N
708,Main Brewery,Greeley,Colorado,UNITED STATES,2018,Y,N
709,Main Brewery,Indianapolis,Indiana,UNITED STATES,2010,Y,N
710,Main Brewery,Carson,Washington,UNITED STATES,2008,N,Y
711,Main Brewery,Austin,Texas,UNITED STATES,2012,Y,N
712,Main Brewery,Torrance,California,UNITED STATES,2013,Y,N
713,Main Brewery,Tampa,Florida,UNITED STATES,2014,Y,N
714,Main Brewery,Hesperia,California,UNITED STATES,2015,Y,N
715,Main Brewery,Minneapolis,Minnesota,UNITED STATES,1997,Y,N
716,Main Brewery,Kill Devil Hills,North Carolina,UNITED STATES,2001,Y,N
717,Main Brewery,Speedway,Indiana,UNITED STATES,2012,Y,N
718,Main Brewery,Taylors,South Carolina,UNITED STATES,2016,Y,N
719,Main Brewery,Spearfish,South Dakota,UNITED STATES,2007,Y,N
720,Main Brewery,Waconia,Minnesota,UNITED STATES,2008,Y,N
721,Main Brewery,Marion,Wisconsin,UNITED STATES,2012,Y,N
722,Main Brewery,Lancaster,Pennsylvania,UNITED STATES,1978,Y,N
723,Main Brewery,Sainte Genevieve,Missouri,UNITED STATES,2008,Y,N
724,Main Brewery,Rincon,Puerto Rico,UNITED STATES,2013,Y,N
725,Main Brewery,Treviso,NaN,NaN,1766,NaN,NaN
726,Main Brewery,San Diego,California,UNITED STATES,2007,Y,N
727,Main Brewery,Aalen,NaN,NaN,1864,NaN,NaN
728,Main Brewery,NaN,NaN,NaN,2011,NaN,NaN
729,Main Brewery,San Diego,California,UNITED STATES,1995,Y,N

In [11]:
df_1 = df2.loc[df2["Country"] == "UNITED STATES"]
df_1

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
0,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N
1,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
2,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N
3,4S Ranch,San Diego,California,UNITED STATES,1989,Y,N
6,7 Mile Brewery,Rio Grande,New Jersey,UNITED STATES,2016,Y,N
7,810 Meadworks,Medina,New York,UNITED STATES,2014,Y,N
8,84th Street Brewing Company,Lake Stevens,Washington,UNITED STATES,2014,Y,N
10,Aberrant Ales,Howell,Michigan,UNITED STATES,2017,Y,N
11,Able Baker Brewing Company,Henderson,Nevada,UNITED STATES,2016,Y,N
12,Accomplice Beer Company,Cheyenne,Wyoming,UNITED STATES,2016,Y,N
13,Addison,Addison,Texas,UNITED STATES,2013,Y,N
14,Adobe Creek Brewing Company,Novato,California,UNITED STATES,2017,Y,N
15,Adventure Brewing North,Fredericksburg,Virginia,UNITED STATES,2013,Y,N
16,Adventure Brewing South,Fredericksburg,Virginia,UNITED STATES,2013,Y,N
18,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N
19,Albany Brewery,Albany,Georgia,UNITED STATES,1895,Y,N
20,127 Brewing,Jackson,Michigan,UNITED STATES,2014,Y,N
21,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N
22,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
23,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N
24,4S Ranch,San Diego,California,UNITED STATES,1989,Y,N
27,7 Mile Brewery,Rio Grande,New Jersey,UNITED STATES,2016,Y,N
28,7th Street Brew House,Redmond,Oregon,UNITED STATES,1994,Y,N
29,810 Meadworks,Medina,New York,UNITED STATES,2014,Y,N
30,84th Street Brewing Company,Lake Stevens,Washington,UNITED STATES,2014,Y,N
34,Aberrant Ales,Howell,Michigan,UNITED STATES,2017,Y,N
35,Able Baker Brewing Company,Henderson,Nevada,UNITED STATES,2016,Y,N
36,Accomplice Beer Company,Cheyenne,Wyoming,UNITED STATES,2016,Y,N
37,Acopon Brewing Company,Dripping Springs,Texas,UNITED STATES,2017,Y,N
38,Adam's NW Bistro & Brewery,Monroe,Washington,UNITED STATES,2011,Y,N
...,...,...,...,...,...,...,...
692,Main Brewery,Colorado Springs,Colorado,UNITED STATES,2014,Y,N
693,Main Brewery,Houston,Texas,UNITED STATES,2014,Y,N
694,Main Brewery,Fort Wayne,Indiana,UNITED STATES,2014,Y,N
695,Main Brewery,Los Angeles,California,UNITED STATES,1997,Y,N
697,Main Brewery,Corvallis,Oregon,UNITED STATES,2010,Y,N
699,Main Brewery,Mount Airy,Maryland,UNITED STATES,2012,Y,N
703,Main Brewery,Centerville,Ohio,UNITED STATES,2012,Y,N
704,Main Brewery,Seattle,Washington,UNITED STATES,2010,Y,N
705,Main Brewery,Pilot Point,Texas,UNITED STATES,2015,Y,N
706,Main Brewery,Pensacola,Florida,UNITED STATES,2017,Y,N
707,Main Brewery,Burbank,California,UNITED STATES,2018,Y,N
708,Main Brewery,Greeley,Colorado,UNITED STATES,2018,Y,N
709,Main Brewery,Indianapolis,Indiana,UNITED STATES,2010,Y,N
710,Main Brewery,Carson,Washington,UNITED STATES,2008,N,Y
711,Main Brewery,Austin,Texas,UNITED STATES,2012,Y,N
712,Main Brewery,Torrance,California,UNITED STATES,2013,Y,N
713,Main Brewery,Tampa,Florida,UNITED STATES,2014,Y,N
714,Main Brewery,Hesperia,California,UNITED STATES,2015,Y,N
715,Main Brewery,Minneapolis,Minnesota,UNITED STATES,1997,Y,N
716,Main Brewery,Kill Devil Hills,North Carolina,UNITED STATES,2001,Y,N
717,Main Brewery,Speedway,Indiana,UNITED STATES,2012,Y,N
718,Main Brewery,Taylors,South Carolina,UNITED STATES,2016,Y,N
719,Main Brewery,Spearfish,South Dakota,UNITED STATES,2007,Y,N
720,Main Brewery,Waconia,Minnesota,UNITED STATES,2008,Y,N
721,Main Brewery,Marion,Wisconsin,UNITED STATES,2012,Y,N
722,Main Brewery,Lancaster,Pennsylvania,UNITED STATES,1978,Y,N
723,Main Brewery,Sainte Genevieve,Missouri,UNITED STATES,2008,Y,N
724,Main Brewery,Rincon,Puerto Rico,UNITED STATES,2013,Y,N
726,Main Brewery,San Diego,California,UNITED STATES,2007,Y,N
729,Main Brewery,San Diego,California,UNITED STATES,1995,Y,N

In [14]:
BrewDF = df_1.reset_index(drop=True)
BrewDF

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
0,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N
1,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
2,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N
3,4S Ranch,San Diego,California,UNITED STATES,1989,Y,N
4,7 Mile Brewery,Rio Grande,New Jersey,UNITED STATES,2016,Y,N
5,810 Meadworks,Medina,New York,UNITED STATES,2014,Y,N
6,84th Street Brewing Company,Lake Stevens,Washington,UNITED STATES,2014,Y,N
7,Aberrant Ales,Howell,Michigan,UNITED STATES,2017,Y,N
8,Able Baker Brewing Company,Henderson,Nevada,UNITED STATES,2016,Y,N
9,Accomplice Beer Company,Cheyenne,Wyoming,UNITED STATES,2016,Y,N
10,Addison,Addison,Texas,UNITED STATES,2013,Y,N
11,Adobe Creek Brewing Company,Novato,California,UNITED STATES,2017,Y,N
12,Adventure Brewing North,Fredericksburg,Virginia,UNITED STATES,2013,Y,N
13,Adventure Brewing South,Fredericksburg,Virginia,UNITED STATES,2013,Y,N
14,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N
15,Albany Brewery,Albany,Georgia,UNITED STATES,1895,Y,N
16,127 Brewing,Jackson,Michigan,UNITED STATES,2014,Y,N
17,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N
18,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
19,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N
20,4S Ranch,San Diego,California,UNITED STATES,1989,Y,N
21,7 Mile Brewery,Rio Grande,New Jersey,UNITED STATES,2016,Y,N
22,7th Street Brew House,Redmond,Oregon,UNITED STATES,1994,Y,N
23,810 Meadworks,Medina,New York,UNITED STATES,2014,Y,N
24,84th Street Brewing Company,Lake Stevens,Washington,UNITED STATES,2014,Y,N
25,Aberrant Ales,Howell,Michigan,UNITED STATES,2017,Y,N
26,Able Baker Brewing Company,Henderson,Nevada,UNITED STATES,2016,Y,N
27,Accomplice Beer Company,Cheyenne,Wyoming,UNITED STATES,2016,Y,N
28,Acopon Brewing Company,Dripping Springs,Texas,UNITED STATES,2017,Y,N
29,Adam's NW Bistro & Brewery,Monroe,Washington,UNITED STATES,2011,Y,N
...,...,...,...,...,...,...,...
522,Main Brewery,Colorado Springs,Colorado,UNITED STATES,2014,Y,N
523,Main Brewery,Houston,Texas,UNITED STATES,2014,Y,N
524,Main Brewery,Fort Wayne,Indiana,UNITED STATES,2014,Y,N
525,Main Brewery,Los Angeles,California,UNITED STATES,1997,Y,N
526,Main Brewery,Corvallis,Oregon,UNITED STATES,2010,Y,N
527,Main Brewery,Mount Airy,Maryland,UNITED STATES,2012,Y,N
528,Main Brewery,Centerville,Ohio,UNITED STATES,2012,Y,N
529,Main Brewery,Seattle,Washington,UNITED STATES,2010,Y,N
530,Main Brewery,Pilot Point,Texas,UNITED STATES,2015,Y,N
531,Main Brewery,Pensacola,Florida,UNITED STATES,2017,Y,N
532,Main Brewery,Burbank,California,UNITED STATES,2018,Y,N
533,Main Brewery,Greeley,Colorado,UNITED STATES,2018,Y,N
534,Main Brewery,Indianapolis,Indiana,UNITED STATES,2010,Y,N
535,Main Brewery,Carson,Washington,UNITED STATES,2008,N,Y
536,Main Brewery,Austin,Texas,UNITED STATES,2012,Y,N
537,Main Brewery,Torrance,California,UNITED STATES,2013,Y,N
538,Main Brewery,Tampa,Florida,UNITED STATES,2014,Y,N
539,Main Brewery,Hesperia,California,UNITED STATES,2015,Y,N
540,Main Brewery,Minneapolis,Minnesota,UNITED STATES,1997,Y,N
541,Main Brewery,Kill Devil Hills,North Carolina,UNITED STATES,2001,Y,N
542,Main Brewery,Speedway,Indiana,UNITED STATES,2012,Y,N
543,Main Brewery,Taylors,South Carolina,UNITED STATES,2016,Y,N
544,Main Brewery,Spearfish,South Dakota,UNITED STATES,2007,Y,N
545,Main Brewery,Waconia,Minnesota,UNITED STATES,2008,Y,N
546,Main Brewery,Marion,Wisconsin,UNITED STATES,2012,Y,N
547,Main Brewery,Lancaster,Pennsylvania,UNITED STATES,1978,Y,N
548,Main Brewery,Sainte Genevieve,Missouri,UNITED STATES,2008,Y,N
549,Main Brewery,Rincon,Puerto Rico,UNITED STATES,2013,Y,N
550,Main Brewery,San Diego,California,UNITED STATES,2007,Y,N
551,Main Brewery,San Diego,California,UNITED STATES,1995,Y,N

In [36]:
brewdf = BrewDF.loc[BrewDF["Year Established"] == (2010)]
brewdf.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
50,Argus Cidery,Austin,Texas,UNITED STATES,2010,Y,N

In [37]:
brewdf1 = BrewDF.loc[BrewDF["Year Established"] == (2011)]
brewdf1.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
1,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N

In [38]:
brewdf2 = BrewDF.loc[BrewDF["Year Established"] == (2012)]
brewdf2.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
43,Amy Seibel,Vancouver,WA - Washington,UNITED STATES,2012,Y,N

In [39]:
brewdf3 = BrewDF.loc[BrewDF["Year Established"] == (2013)]
brewdf3.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
10,Addison,Addison,Texas,UNITED STATES,2013,Y,N

In [40]:
brewdf4 = BrewDF.loc[BrewDF["Year Established"] == (2014)]
brewdf4.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
0,4 Seasons Brewery,Lapeer,Michigan,UNITED STATES,2014,Y,N

In [41]:
brewdf5 = BrewDF.loc[BrewDF["Year Established"] == (2015)]
brewdf5.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
62,Axle Brewing Company,Ferndale,Michigan,UNITED STATES,2015,Y,N

In [42]:
brewdf6 = BrewDF.loc[BrewDF["Year Established"] == (2016)]
brewdf6.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
2,4kd Crick Brewery,Defiance,Ohio,UNITED STATES,2016,Y,N

In [43]:
brewdf7 = BrewDF.loc[BrewDF["Year Established"] == (2017)]
brewdf7.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
7,Aberrant Ales,Howell,Michigan,UNITED STATES,2017,Y,N

In [44]:
brewdf8 = BrewDF.loc[BrewDF["Year Established"] == (2018)]
brewdf8.head(1)

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
14,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N

In [45]:
DF1s = [brewdf, brewdf1, brewdf2, brewdf3, brewdf4, brewdf5, brewdf6, brewdf7, brewdf8]

In [48]:
BreweryDF = pd.concat(DF1s, axis=0)
BreweryDF

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
50,Argus Cidery,Austin,Texas,UNITED STATES,2010,Y,N
51,Armadillo Ale Works,Denton,Texas,UNITED STATES,2010,Y,N
83,Biergarten,Salem,Massachusetts,UNITED STATES,2010,Y,N
98,Brewery & Restaurant,Falls Church,Virginia,UNITED STATES,2010,Y,N
120,Buellton Taproom,Buellton,California,UNITED STATES,2010,Y,N
136,Bushwhacker Cider - Brooklyn,Portland,Oregon,UNITED STATES,2010,Y,N
137,Bushwhacker Cider - Woodlawn,Portland,Oregon,UNITED STATES,2010,Y,N
229,Funky Buddha Brewery,Oakland Park,Florida,UNITED STATES,2010,Y,N
245,Good Nature Farm Brewery,Hamilton,New York,UNITED STATES,2010,Y,N
246,Good Nature Tap Room,Hamilton,New York,UNITED STATES,2010,Y,N
256,Gremps Street Alehouse,Paw Paw,Michigan,UNITED STATES,2010,Y,N
319,Main Brewery,Norfolk,Virginia,UNITED STATES,2010,Y,N
324,Main Brewery,Lubbock,Texas,UNITED STATES,2010,Y,N
351,Main Brewery,Loveland,Colorado,UNITED STATES,2010,Y,N
352,Main Brewery,Santee,California,UNITED STATES,2010,Y,N
355,Main Brewery,Grand Rapids,Michigan,UNITED STATES,2010,Y,N
372,Main Brewery,Arcata,California,UNITED STATES,2010,Y,N
383,Main Brewery,Grand Haven,Michigan,UNITED STATES,2010,Y,N
421,Main Brewery,Ridgefield Park,New Jersey,UNITED STATES,2010,Y,N
447,Main Brewery,Anchorage,Alaska,UNITED STATES,2010,Y,N
495,Main Brewery,Longview,Washington,UNITED STATES,2010,Y,N
503,Main Brewery,Marquette,Michigan,UNITED STATES,2010,Y,N
505,Main Brewery,Orcutt,California,UNITED STATES,2010,Y,N
521,Main Brewery,Covington,Louisiana,UNITED STATES,2010,Y,N
526,Main Brewery,Corvallis,Oregon,UNITED STATES,2010,Y,N
529,Main Brewery,Seattle,Washington,UNITED STATES,2010,Y,N
534,Main Brewery,Indianapolis,Indiana,UNITED STATES,2010,Y,N
1,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
18,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
29,Adam's NW Bistro & Brewery,Monroe,Washington,UNITED STATES,2011,Y,N
...,...,...,...,...,...,...,...
282,Lawrence Beer Company,Lawrence,Kansas,UNITED STATES,2017,Y,N
295,Long Beach,Long Beach,California,UNITED STATES,2017,Y,N
297,Long Table Brewhouse,Denver,Colorado,UNITED STATES,2017,Y,N
364,Main Brewery,Clarksville,Tennessee,UNITED STATES,2017,Y,N
369,Main Brewery,Minnetonka,Minnesota,UNITED STATES,2017,Y,N
400,Main Brewery,Chicago,Illinois,UNITED STATES,2017,Y,N
451,Main Brewery,Farmville,Virginia,UNITED STATES,2017,Y,N
471,Main Brewery,Largo,Florida,UNITED STATES,2017,N,Y
472,Main Brewery,Williamsport,Pennsylvania,UNITED STATES,2017,Y,N
507,Main Brewery,Austin,Texas,UNITED STATES,2017,Y,N
531,Main Brewery,Pensacola,Florida,UNITED STATES,2017,Y,N
14,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N
36,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N
45,Angry James Brewery,Silverthorne,Colorado,UNITED STATES,2018,Y,N
111,Brews Angels Brewery,Milton,Florida,UNITED STATES,2018,Y,N
119,BruWorx Mead & Cider,Troy,Michigan,UNITED STATES,2018,Y,N
131,Burns Family Artisan Ales,Denver,Colorado,UNITED STATES,2018,Y,N
194,Flyover Brewing Company,Scottsbluff,Nebraska,UNITED STATES,2018,Y,N
200,Fort Brewery and Pizza,Fort Worth,Texas,UNITED STATES,2018,Y,N
233,Garrett's Brewery Company,Trumansburg,New York,UNITED STATES,2018,Y,N
274,Imperial Western Beer Company,Los Angeles,California,UNITED STATES,2018,Y,N
300,Look Long Brewing Company,POrtland,Oregon,UNITED STATES,2018,Y,N
312,Mad Paddle Brewery,Madison,Indiana,UNITED STATES,2018,Y,N
344,Main Brewery,Clarksville,Tennessee,UNITED STATES,2018,Y,N
350,Main Brewery,San Diego,California,UNITED STATES,2018,Y,N
371,Main Brewery,Albion,Michigan,UNITED STATES,2018,Y,N
391,Main Brewery,Alexandria,Louisiana,UNITED STATES,2018,Y,N
519,Main Brewery,Dallas,Texas,UNITED STATES,2018,Y,N
532,Main Brewery,Burbank,California,UNITED STATES,2018,Y,N
533,Main Brewery,Greeley,Colorado,UNITED STATES,2018,Y,N

In [50]:
BreweryDFs = BreweryDF.reset_index(drop=True)
BreweryDFs

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
0,Argus Cidery,Austin,Texas,UNITED STATES,2010,Y,N
1,Armadillo Ale Works,Denton,Texas,UNITED STATES,2010,Y,N
2,Biergarten,Salem,Massachusetts,UNITED STATES,2010,Y,N
3,Brewery & Restaurant,Falls Church,Virginia,UNITED STATES,2010,Y,N
4,Buellton Taproom,Buellton,California,UNITED STATES,2010,Y,N
5,Bushwhacker Cider - Brooklyn,Portland,Oregon,UNITED STATES,2010,Y,N
6,Bushwhacker Cider - Woodlawn,Portland,Oregon,UNITED STATES,2010,Y,N
7,Funky Buddha Brewery,Oakland Park,Florida,UNITED STATES,2010,Y,N
8,Good Nature Farm Brewery,Hamilton,New York,UNITED STATES,2010,Y,N
9,Good Nature Tap Room,Hamilton,New York,UNITED STATES,2010,Y,N
10,Gremps Street Alehouse,Paw Paw,Michigan,UNITED STATES,2010,Y,N
11,Main Brewery,Norfolk,Virginia,UNITED STATES,2010,Y,N
12,Main Brewery,Lubbock,Texas,UNITED STATES,2010,Y,N
13,Main Brewery,Loveland,Colorado,UNITED STATES,2010,Y,N
14,Main Brewery,Santee,California,UNITED STATES,2010,Y,N
15,Main Brewery,Grand Rapids,Michigan,UNITED STATES,2010,Y,N
16,Main Brewery,Arcata,California,UNITED STATES,2010,Y,N
17,Main Brewery,Grand Haven,Michigan,UNITED STATES,2010,Y,N
18,Main Brewery,Ridgefield Park,New Jersey,UNITED STATES,2010,Y,N
19,Main Brewery,Anchorage,Alaska,UNITED STATES,2010,Y,N
20,Main Brewery,Longview,Washington,UNITED STATES,2010,Y,N
21,Main Brewery,Marquette,Michigan,UNITED STATES,2010,Y,N
22,Main Brewery,Orcutt,California,UNITED STATES,2010,Y,N
23,Main Brewery,Covington,Louisiana,UNITED STATES,2010,Y,N
24,Main Brewery,Corvallis,Oregon,UNITED STATES,2010,Y,N
25,Main Brewery,Seattle,Washington,UNITED STATES,2010,Y,N
26,Main Brewery,Indianapolis,Indiana,UNITED STATES,2010,Y,N
27,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
28,40 North Brewing,Boulder,Colorado,UNITED STATES,2011,Y,N
29,Adam's NW Bistro & Brewery,Monroe,Washington,UNITED STATES,2011,Y,N
...,...,...,...,...,...,...,...
314,Lawrence Beer Company,Lawrence,Kansas,UNITED STATES,2017,Y,N
315,Long Beach,Long Beach,California,UNITED STATES,2017,Y,N
316,Long Table Brewhouse,Denver,Colorado,UNITED STATES,2017,Y,N
317,Main Brewery,Clarksville,Tennessee,UNITED STATES,2017,Y,N
318,Main Brewery,Minnetonka,Minnesota,UNITED STATES,2017,Y,N
319,Main Brewery,Chicago,Illinois,UNITED STATES,2017,Y,N
320,Main Brewery,Farmville,Virginia,UNITED STATES,2017,Y,N
321,Main Brewery,Largo,Florida,UNITED STATES,2017,N,Y
322,Main Brewery,Williamsport,Pennsylvania,UNITED STATES,2017,Y,N
323,Main Brewery,Austin,Texas,UNITED STATES,2017,Y,N
324,Main Brewery,Pensacola,Florida,UNITED STATES,2017,Y,N
325,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N
326,Alaro Craft Brewery,Sacramento,California,UNITED STATES,2018,Y,N
327,Angry James Brewery,Silverthorne,Colorado,UNITED STATES,2018,Y,N
328,Brews Angels Brewery,Milton,Florida,UNITED STATES,2018,Y,N
329,BruWorx Mead & Cider,Troy,Michigan,UNITED STATES,2018,Y,N
330,Burns Family Artisan Ales,Denver,Colorado,UNITED STATES,2018,Y,N
331,Flyover Brewing Company,Scottsbluff,Nebraska,UNITED STATES,2018,Y,N
332,Fort Brewery and Pizza,Fort Worth,Texas,UNITED STATES,2018,Y,N
333,Garrett's Brewery Company,Trumansburg,New York,UNITED STATES,2018,Y,N
334,Imperial Western Beer Company,Los Angeles,California,UNITED STATES,2018,Y,N
335,Look Long Brewing Company,POrtland,Oregon,UNITED STATES,2018,Y,N
336,Mad Paddle Brewery,Madison,Indiana,UNITED STATES,2018,Y,N
337,Main Brewery,Clarksville,Tennessee,UNITED STATES,2018,Y,N
338,Main Brewery,San Diego,California,UNITED STATES,2018,Y,N
339,Main Brewery,Albion,Michigan,UNITED STATES,2018,Y,N
340,Main Brewery,Alexandria,Louisiana,UNITED STATES,2018,Y,N
341,Main Brewery,Dallas,Texas,UNITED STATES,2018,Y,N
342,Main Brewery,Burbank,California,UNITED STATES,2018,Y,N
343,Main Brewery,Greeley,Colorado,UNITED STATES,2018,Y,N

In [51]:
BreweryDFs.to_csv("Output/BreweryData.csv", encoding="utf-8", index=False, header=True)

In [56]:
Closed = BreweryDFs.loc[BreweryDFs["Closed?"] == "Y"]
Closed

,Brewery Name,City,State,Country,Year Established,In Business?,Closed?
32,Bus,Tampa,Florida,UNITED STATES,2011,Y,Y
48,Main Brewery,Bend,Oregon,UNITED STATES,2011,N,Y
63,Main Brewery,Fayetteville,Arkansas,UNITED STATES,2011,N,Y
65,Main Brewery,Garden City,Idaho,UNITED STATES,2011,N,Y
92,Main Brewery,Ava,Illinois,UNITED STATES,2012,N,Y
103,Main Brewery,Carbondale,Pennsylvania,UNITED STATES,2012,N,Y
121,Bravo Zulu Brewing,N Williamsburg,Michigan,UNITED STATES,2013,N,Y
122,Brewpub,Boulder,Colorado,UNITED STATES,2013,N,Y
151,Main Brewery,Lewisville,Texas,UNITED STATES,2013,N,Y
161,Main Brewery,Chicago,Illinois,UNITED STATES,2013,N,Y
186,Former Future Brewing Company,Denver,Colorado,UNITED STATES,2014,N,Y
192,Main Brewery,Aurora,Colorado,UNITED STATES,2014,N,Y
214,Main Brewery,Aurora,Colorado,UNITED STATES,2014,N,Y
221,Beer Army Outpost,New Bern,North Carolina,UNITED STATES,2015,N,Y
239,Main Brewery,Chama,New Mexico,UNITED STATES,2015,N,Y
242,Main Brewery,Agoura Hills,California,UNITED STATES,2015,N,Y
248,Main Brewery,Fremont,Michigan,UNITED STATES,2015,N,Y
253,Main Brewery,Woodbridge,Virginia,UNITED STATES,2015,N,Y
321,Main Brewery,Largo,Florida,UNITED STATES,2017,N,Y

In [57]:
Closed.to_csv("Output/Closed.csv", encoding="utf-8", index=False, header=True)

In [58]:
Brew = BreweryDFs.groupby(["State"])

In [66]:
Brew_count = Brew.count()

Brew_count

,Brewery Name,City,Country,Year Established,In Business?,Closed?
State,,,,,,
Alabama,2,2,2,2,2,2
Alaska,1,1,1,1,1,1
Arizona,6,6,6,6,6,6
Arkansas,2,2,2,2,2,2
California,50,50,50,50,50,50
Colorado,27,27,27,27,27,27
Connecticut,1,1,1,1,1,1
Delaware,2,2,2,2,2,2
Deleware,1,1,1,1,1,1
Florida,13,13,13,13,13,13
Georgia,1,1,1,1,1,1
Idaho,7,7,7,7,7,7
Illinois,8,8,8,8,8,8
Indiana,11,11,11,11,11,11
Iowa,5,5,5,5,5,5
Kansas,1,1,1,1,1,1
Kentucky,2,2,2,2,2,2
Louisiana,3,3,3,3,3,3
Maryland,3,3,3,3,3,3
Massachusetts,5,5,5,5,5,5
Michigan,28,28,28,28,28,28
Minnesota,5,5,5,5,5,5
Missouri,3,3,3,3,3,3
Montana,2,2,2,2,2,2
Nebraska,3,3,3,3,3,3
Nevada,3,3,3,3,3,3
New Hampshire,3,3,3,3,3,3
New Jersey,4,4,4,4,4,4
New Mexico,3,3,3,3,3,3
New York,12,12,12,12,12,12
North Carolina,14,14,14,14,14,14
Ohio,8,8,8,8,8,8
Oregon,14,14,14,14,14,14
Pennsylvania,11,11,11,11,11,11
Puerto Rico,1,1,1,1,1,1
Rhode Island,1,1,1,1,1,1
South Carolina,5,5,5,5,5,5
South Dakota,1,1,1,1,1,1
Tennessee,4,4,4,4,4,4
Tennesssee,1,1,1,1,1,1
Texas,27,27,27,27,27,27
Utah,1,1,1,1,1,1
Vermont,1,1,1,1,1,1
Virginia,15,15,15,15,15,15
WA - Washington,1,1,1,1,1,1
Washington,13,13,13,13,13,13
West Virginia,1,1,1,1,1,1
Wisconsin,4,4,4,4,4,4
Wyoming,3,3,3,3,3,3
illinois,1,1,1,1,1,1

In [68]:
Brew_count.to_csv("Output/Count.csv", encoding="utf-8", index=False, header=True)